   services:
     wallet:
       depends_on:
         - postgres
       restart: always
       build:
         context: .
       image: wallet1.0
       container_name: wallet
       networks:
         - my-local-net
       ports:
         - 8088:8088
       

     postgres:
       image: postgres:latest
       container_name: postgres_container
       networks:
         - my-local-net
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: Tatsh
         POSTGRES_DB: wallet
       ports:
         - "5432:5432"
       volumes:
         - ./pgdata:/var/lib/postgresql/data
   volumes:
     pgdata:
       driver: local
   networks:
       my-local-net:
         name: mynet
         driver: bridge